name: Maven Library Publish
permissions:
  contents: read

on:
  release:
    types: [created]
  workflow_dispatch:  

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v3

      # 2️⃣ Set up JDK 21
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3️⃣ Configure Maven settings with OSSRH credentials
      - name: Configure Maven settings
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_TOKEN_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN_PASSWORD }}
        run: |
          mkdir -p $HOME/.m2
          cat <<EOF > $HOME/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>central</id>
                <username>${OSSRH_USERNAME}</username>
                <password>${OSSRH_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          EOF

      # 4️⃣ Deploy to OSSRH staging with Simplify4U signing
      - name: Deploy to OSSRH staging
        env:
          SIGN_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          SIGN_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          SIGN_KEY_PASS: ${{ secrets.GPG_PASSPHRASE }}
        run: mvn clean deploy -B
