name: Maven Library Publish
permissions:
  contents: read

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v3

      # 2️⃣ Set up Java 21 and Maven
      - name: Set up Java 21 and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      # 3️⃣ Deploy to OSSRH with Simplify4U signing
      - name: Deploy to OSSRH staging
        env:
          SIGN_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          SIGN_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          SIGN_KEY_PASS: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        run: mvn clean deploy -B
