name: Maven Library Publish

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v3

      # 2️⃣ Set up Java 21 and Maven
      - name: Set up Java 21 and Maven
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          server-id: central
          server-username: ${{ secrets.OSSRH_TOKEN_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN_PASSWORD }}

      # 3️⃣ Deploy to OSSRH staging
      - name: Deploy to OSSRH staging
        env:
          SIGN_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          SIGN_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          SIGN_KEY_PASS: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_TOKEN_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN_PASSWORD }}
        run: mvn clean deploy -B
