name: Maven Library Publish
permissions:
  contents: read

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v3

      # 2️⃣ Set up JDK 21 and Maven with credentials and GPG keys
      - name: Set up Java 21 and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          server-id: central
          server-username: ${{ secrets.OSSRH_TOKEN_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # 3️⃣ Deploy to Sonatype OSSRH staging repository
      - name: Deploy to OSSRH staging
        run: mvn clean deploy
